### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by pol-todo** [uscensusbureau/BEACON#1]
Hi all,

I was curious why the source code isn't listed here? (Also, where might it be?)

**Comment by brian-dumbacher** [comment]
Hello.  We have uploaded a Python program that implements a simplified version of BEACON.  This implementation uses scikit-learn's BaseEstimator and ClassifierMixin classes.

**Comment by pol-todo** [comment]
@brian-dumbacher Brilliant! This was the last part of the puzzle for our research paper! Does the project team have a preference for academic citation info? (e.g. Should we reference the repo, or perhaps the presentation would be best?)

**Comment by brian-dumbacher** [comment]
@paulterinho Please cite this recently uploaded working paper: https://www2.census.gov/library/working-papers/2024/econ/industry-self-classification-economic-census.pdf. Thank you for your interest, and good luck with your research.

**Comment by paultrino** [comment]
@brian-dumbacher Perfect, will do!
