### ISSUE TITLE
Indicies need to be reversed for x and y in beacon.py

### ISSUE THREAD

**Issue by paultrino** [uscensusbureau/BEACON#2]
Hi @brian-dumbacher  Found a tiny bug located in `beacon.py`, the indices (0 and 1) need to be reversed for `x` and `y` at line 112, to look like this...
```
    # Create X, y, and sample_weight
    X = np.array([tup[1] for tup in data_tups])
    y = np.array([tup[0] for tup in data_tups])
```

**Comment by brian-dumbacher** [comment]
Hi, @paultrino.  Thanks for spotting that.  ```beacon.py``` expects the variables in the example datasets to be ordered TEXT, NAICS, and SAMPLE_WEIGHT (optional).  ```create_example_data.py``` was creating the example datasets with TEXT and NAICS in reverse order.  I've uploaded a corrected version of ```create_example_data.py``` to work with ```beacon.py``` as it is.

**Comment by paultrino** [comment]
Hi @brian-dumbacher No problem at all. Thanks posting these great examples!
